### PR TITLE
Enable offloaded MKL execution.

### PR DESCRIPTION
**Pull request by vzakhari**
Data mapping was hoisted out of the loop to improve timing.
Changed Makefile to use proper options for mkl.

### CODE REVIEW

**Comment by vzakhari** [comment]
@jeffhammond can you please review/merge this?

**Review by jeffhammond — APPROVED** [review]

**Comment by jeffhammond** [comment]
The `-qmkl` flag doesn't work with 2021.1.2 and the code doesn't terminate on `ortce-nucg`.  Where did you test this?

**Comment by vzakhari** [comment]
> The `-qmkl` flag doesn't work with 2021.1.2 and the code doesn't terminate on `ortce-nucg`. Where did you test this?

Sorry for the delay.  I tested it with an engineering compiler. @mdtoguchi, should `-qmkl` be available in any released product already?

**Comment by mdtoguchi** [comment]
> > The `-qmkl` flag doesn't work with 2021.1.2 and the code doesn't terminate on `ortce-nucg`. Where did you test this?
> 
> Sorry for the delay. I tested it with an engineering compiler. @mdtoguchi, should `-qmkl` be available in any released product already?

Should be available in Update 1.

**Comment by jeffhammond** [comment]
I merged this without testing it because I don't have access to any computers with the right hardware and software anymore.  I'll test on Argonne JLSE once I get a change.

**Pull request merged**
